import { Product, BlogPost } from './types'

export const products: Product[] = [
  {
    id: '1',
    handle: 'camo-star-oversized-t-shirt',
    title: 'Camo Star Oversized T-shirt',
    description: 'Bold camo star print oversized t-shirt crafted from premium cotton.',
    price: 999,
    compareAtPrice: 1299,
    images: ['/images/products/product-1.svg'],
    category: 'women',
    collection: ['new-arrivals', 'oversized-t-shirts'],
    tags: ['camo', 'star', 'oversized'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Green'],
    isNew: true,
    badge: 'sale',
  },
  {
    id: '2',
    handle: 'local-celebrity-oversized-t-shirt',
    title: 'Local Celebrity Oversized T-shirt',
    description: 'Be the local celebrity in this bold oversized tee.',
    price: 999,
    compareAtPrice: 1299,
    images: ['/images/products/product-2.svg'],
    category: 'women',
    collection: ['new-arrivals', 'oversized-t-shirts'],
    tags: ['celebrity', 'oversized'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    isNew: true,
    badge: 'sale',
  },
  {
    id: '3',
    handle: 'charcoal-blur-pants',
    title: 'Charcoal Blur Pants',
    description: 'Premium charcoal blur pants for a sleek streetwear look.',
    price: 1499,
    compareAtPrice: 1899,
    images: ['/images/products/product-3.svg'],
    category: 'men',
    collection: ['new-arrivals', 'bottoms'],
    tags: ['charcoal', 'pants'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal'],
    isNew: true,
    badge: 'sale',
  },
  {
    id: '4',
    handle: 'dash-denim-jacket',
    title: 'Dash Denim Jacket',
    description: 'Classic denim jacket with a modern oversized fit.',
    price: 2299,
    compareAtPrice: 2399,
    images: ['/images/products/product-4.svg'],
    category: 'women',
    collection: ['new-arrivals', 'jackets'],
    tags: ['denim', 'jacket'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue'],
    badge: 'new',
  },
  {
    id: '5',
    handle: 'edge-line-baggy-fit-jeans',
    title: 'Edge Line Baggy Fit Jeans',
    description: 'Relaxed baggy fit jeans with edge line detailing.',
    price: 1899,
    compareAtPrice: 1999,
    images: ['/images/products/product-5.svg'],
    category: 'men',
    collection: ['new-arrivals', 'jeans'],
    tags: ['baggy', 'jeans'],
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Blue'],
    badge: 'sale',
  },
  {
    id: '6',
    handle: 'motion-frequency-jacket',
    title: 'Motion Frequency Jacket',
    description: 'Premium motion frequency jacket with technical fabric.',
    price: 2999,
    compareAtPrice: 3199,
    images: ['/images/products/product-6.svg'],
    category: 'men',
    collection: ['new-arrivals', 'jackets'],
    tags: ['jacket', 'technical'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    badge: 'sale',
  },
  {
    id: '7',
    handle: 'flushing-pink-trackline-joggers',
    title: 'Flushing Pink Trackline Joggers',
    description: 'Vibrant pink joggers with trackline detailing.',
    price: 1499,
    compareAtPrice: 1899,
    images: ['/images/products/product-7.svg'],
    category: 'women',
    collection: ['new-arrivals', 'joggers'],
    tags: ['pink', 'joggers'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Pink'],
    badge: 'sale',
  },
  {
    id: '8',
    handle: 'moddy-blue-trackline-joggers',
    title: 'Moddy Blue Trackline Joggers',
    description: 'Premium blue joggers for effortless streetwear style.',
    price: 1499,
    compareAtPrice: 1899,
    images: ['/images/products/product-8.svg'],
    category: 'men',
    collection: ['new-arrivals', 'joggers'],
    tags: ['blue', 'joggers'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    badge: 'sale',
  },
  {
    id: '9',
    handle: 'black-loose-fit-joggers',
    title: 'Black Loose Fit Joggers',
    description: 'Classic black loose fit joggers for everyday comfort.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['/images/products/product-9.svg'],
    category: 'men',
    collection: ['best-sellers', 'joggers'],
    tags: ['black', 'joggers'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    isBestseller: true,
    badge: 'bestseller',
  },
  {
    id: '10',
    handle: 'olive-tape-wide-leg-joggers',
    title: 'Olive Tape Wide Leg Joggers',
    description: 'Wide leg joggers with tape detailing in olive.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['/images/products/product-10.svg'],
    category: 'men',
    collection: ['best-sellers', 'joggers'],
    tags: ['olive', 'joggers'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Olive'],
    isBestseller: true,
    badge: 'bestseller',
  },
  {
    id: '11',
    handle: 'everyday-sailor-stripe-oversized-t-shirt',
    title: 'Everyday Sailor Stripe Oversized T-shirt',
    description: 'Nautical-inspired sailor stripe oversized tee.',
    price: 1099,
    compareAtPrice: 1299,
    images: ['/images/products/product-11.svg'],
    category: 'men',
    collection: ['best-sellers', 'oversized-t-shirts'],
    tags: ['stripe', 'sailor', 'oversized'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White'],
    isBestseller: true,
    badge: 'bestseller',
  },
  {
    id: '12',
    handle: 'black-faded-loose-fit-pants',
    title: 'Black Faded Loose Fit Pants',
    description: 'Faded black loose fit pants for a vintage look.',
    price: 1499,
    compareAtPrice: 1799,
    images: ['/images/products/product-12.svg'],
    category: 'women',
    collection: ['women', 'bottoms'],
    tags: ['black', 'faded', 'pants'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black'],
  },
  {
    id: '13',
    handle: 'black-wide-leg-sweatpants',
    title: 'Black Wide-Leg Sweatpants',
    description: 'Comfortable wide-leg sweatpants in black.',
    price: 1199,
    compareAtPrice: 1499,
    images: ['/images/products/product-13.svg'],
    category: 'women',
    collection: ['women', 'bottoms'],
    tags: ['black', 'sweatpants'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black'],
  },
  {
    id: '14',
    handle: 'sand-beige-wide-leg-sweatpants',
    title: 'Sand Beige Wide-Leg Sweatpants',
    description: 'Soft sand beige wide-leg sweatpants.',
    price: 1199,
    compareAtPrice: 1499,
    images: ['/images/products/product-14.svg'],
    category: 'women',
    collection: ['women', 'bottoms'],
    tags: ['beige', 'sweatpants'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Beige'],
  },
  {
    id: '15',
    handle: 'kid-98-cap',
    title: 'Kid 98 Cap',
    description: 'Classic 98 cap with kid branding.',
    price: 799,
    compareAtPrice: 1099,
    images: ['/images/products/product-15.svg'],
    category: 'accessories',
    collection: ['caps'],
    tags: ['cap', 'kid'],
    sizes: ['One Size'],
    colors: ['Black'],
    badge: 'sale',
  },
  {
    id: '16',
    handle: 'soft-yellow-oversized-t-shirt',
    title: 'Soft Yellow Oversized T-shirt',
    description: 'Soft yellow oversized t-shirt for a fresh summer look.',
    price: 999,
    compareAtPrice: 1299,
    images: ['/images/products/product-16.svg'],
    category: 'men',
    collection: ['new-arrivals', 'oversized-t-shirts'],
    tags: ['yellow', 'oversized'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Yellow'],
    badge: 'sale',
  },
  {
    id: '17',
    handle: 'iron-grey-oversized-t-shirt',
    title: 'Iron Grey Oversized T-shirt',
    description: 'Premium iron grey oversized t-shirt.',
    price: 999,
    compareAtPrice: 1299,
    images: ['/images/products/product-17.svg'],
    category: 'men',
    collection: ['new-arrivals', 'oversized-t-shirts'],
    tags: ['grey', 'oversized'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Grey'],
    badge: 'sale',
  },
  {
    id: '18',
    handle: 'blissful-blue-loose-fit-joggers',
    title: 'Blissful Blue Loose Fit Joggers',
    description: 'Comfortable blue loose fit joggers.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['/images/products/product-18.svg'],
    category: 'men',
    collection: ['new-arrivals', 'joggers'],
    tags: ['blue', 'joggers'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    badge: 'sale',
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    handle: 'gift-ideas-for-raksha-bandhan',
    title: 'Gift Ideas for Raksha Bandhan: Celebrate Your Sibling Bond in MARVVN Style',
    excerpt: 'Raksha Bandhan just got better. Explore stylish gift ideas for your sibling, from oversized T-shirts and cargos to co-ords, bags and accessories.',
    image: '/images/blog/post-1.svg',
    date: 'August 22 2026',
    author: 'MARVVN',
    tags: ['gifting', 'raksha-bandhan', 'style'],
  },
  {
    id: '2',
    handle: 'how-to-style-cargo-pants',
    title: 'How to Style Cargo Pants for an Effortlessly Balanced Look',
    excerpt: 'Cargo pants are doing the heavy lifting literally. From oversized streetwear fits to polished everyday looks, discover easy ways to style cargos.',
    image: '/images/blog/post-2.svg',
    date: 'August 13 2026',
    author: 'MARVVN',
    tags: ['cargo', 'styling', 'menswear'],
  },
  {
    id: '3',
    handle: 'spiderman-movie-outfit-ideas',
    title: 'What to Wear to the Spider-Man Movie: Spiderman Outfit Ideas',
    excerpt: 'Your ticket is booked now complete the mission! Explore Spider-Man movie outfit ideas that will have every Marvel fan turning heads.',
    image: '/images/blog/post-3.svg',
    date: 'July 25 2026',
    author: 'MARVVN',
    tags: ['marvel', 'spiderman', 'outfit'],
  },
]

export const collections = [
  { id: '1', handle: 'new-arrivals', title: 'New Arrivals', description: 'Latest drops and fresh fits' },
  { id: '2', handle: 'best-sellers', title: 'Best Sellers', description: 'Handpicked and crafted for you' },
  { id: '3', handle: 'oversized-t-shirts', title: 'Oversized T-Shirts', description: 'Premium oversized tees' },
  { id: '4', handle: 'bottoms', title: 'Bottoms', description: 'Joggers, pants, and more' },
  { id: '5', handle: 'jackets', title: 'Jackets', description: 'Layer up in style' },
  { id: '6', handle: 'caps', title: 'Caps', description: 'Top off your look' },
]
