import { Product, BlogPost } from './types'

export const products: Product[] = [
  {
    id: '1',
    handle: 'camo-star-oversized-t-shirt',
    title: 'Camo Star Oversized T-shirt',
    description: 'Bold camo star print oversized t-shirt crafted from premium cotton.',
    price: 999,
    compareAtPrice: 1299,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/1_jpg_800x.jpg?v=1787746719'],
    category: 'women',
    collection: ['new-arrivals', 'oversized-t-shirts'],
    tags: ['camo', 'star', 'oversized'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Green'],
    isNew: true,
    badge: 'sale',
  },
  {
    id: '2',
    handle: 'local-celebrity-oversized-t-shirt',
    title: 'Local Celebrity Oversized T-shirt',
    description: 'Be the local celebrity in this bold oversized tee.',
    price: 999,
    compareAtPrice: 1299,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/LocalCelebrityOversizedT-shirt4_800x.jpg?v=1787825540'],
    category: 'women',
    collection: ['new-arrivals', 'oversized-t-shirts'],
    tags: ['celebrity', 'oversized'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    isNew: true,
    badge: 'sale',
  },
  {
    id: '3',
    handle: 'charcoal-blur-pants',
    title: 'Charcoal Blur Pants',
    description: 'Premium charcoal blur pants for a sleek streetwear look.',
    price: 1499,
    compareAtPrice: 1899,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/15_655517a2-e65a-465b-98dd-5ad60800b4dd_800x.jpg?v=1787832274'],
    category: 'men',
    collection: ['new-arrivals', 'bottoms'],
    tags: ['charcoal', 'pants'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal'],
    isNew: true,
    badge: 'sale',
  },
  {
    id: '4',
    handle: 'dash-denim-jacket',
    title: 'Dash Denim Jacket',
    description: 'Classic denim jacket with a modern oversized fit.',
    price: 2299,
    compareAtPrice: 2399,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/Dashdenimjacket_8_800x.jpg?v=1787567371'],
    category: 'women',
    collection: ['new-arrivals', 'jackets'],
    tags: ['denim', 'jacket'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue'],
    badge: 'new',
  },
  {
    id: '5',
    handle: 'edge-line-baggy-fit-jeans',
    title: 'Edge Line Baggy Fit Jeans',
    description: 'Relaxed baggy fit jeans with edge line detailing.',
    price: 1899,
    compareAtPrice: 1999,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/EdgeLineBaggyFitJeans_2_800x.jpg?v=1787568639'],
    category: 'men',
    collection: ['new-arrivals', 'jeans'],
    tags: ['baggy', 'jeans'],
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Blue'],
    badge: 'sale',
  },
  {
    id: '6',
    handle: 'motion-frequency-jacket',
    title: 'Motion Frequency Jacket',
    description: 'Premium motion frequency jacket with technical fabric.',
    price: 2999,
    compareAtPrice: 3199,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/File14_800x.png?v=1787391971'],
    category: 'men',
    collection: ['new-arrivals', 'jackets'],
    tags: ['jacket', 'technical'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    badge: 'sale',
  },
  {
    id: '7',
    handle: 'flushing-pink-trackline-joggers',
    title: 'Flushing Pink Trackline Joggers',
    description: 'Vibrant pink joggers with trackline detailing.',
    price: 1499,
    compareAtPrice: 1899,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/FlushingPinktracklinejoggers_7_800x.jpg?v=1787286820'],
    category: 'women',
    collection: ['new-arrivals', 'joggers'],
    tags: ['pink', 'joggers'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Pink'],
    badge: 'sale',
  },
  {
    id: '8',
    handle: 'moddy-blue-trackline-joggers',
    title: 'Moddy Blue Trackline Joggers',
    description: 'Premium blue joggers for effortless streetwear style.',
    price: 1499,
    compareAtPrice: 1899,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/ModdyBlueTracklineJoggers_9_0a463989-82ed-4371-b610-31e19d713ce8_800x.jpg?v=1787286397'],
    category: 'men',
    collection: ['new-arrivals', 'joggers'],
    tags: ['blue', 'joggers'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    badge: 'sale',
  },
  {
    id: '9',
    handle: 'black-loose-fit-joggers',
    title: 'Black Loose Fit Joggers',
    description: 'Classic black loose fit joggers for everyday comfort.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/BlackLooseFitJoggers_3_800x.png?v=1783420776'],
    category: 'men',
    collection: ['best-sellers', 'joggers'],
    tags: ['black', 'joggers'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    isBestseller: true,
    badge: 'bestseller',
  },
  {
    id: '10',
    handle: 'olive-tape-wide-leg-joggers',
    title: 'Olive Tape Wide Leg Joggers',
    description: 'Wide leg joggers with tape detailing in olive.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/OliveTapeWideLegJoggers_4_800x.png?v=1784794518'],
    category: 'men',
    collection: ['best-sellers', 'joggers'],
    tags: ['olive', 'joggers'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Olive'],
    isBestseller: true,
    badge: 'bestseller',
  },
  {
    id: '11',
    handle: 'everyday-sailor-stripe-oversized-t-shirt',
    title: 'Everyday Sailor Stripe Oversized T-shirt',
    description: 'Nautical-inspired sailor stripe oversized tee.',
    price: 1099,
    compareAtPrice: 1299,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/EverydaySailorStripeOversizedT-shirt_5_800x.jpg?v=1786083989'],
    category: 'men',
    collection: ['best-sellers', 'oversized-t-shirts'],
    tags: ['stripe', 'sailor', 'oversized'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White'],
    isBestseller: true,
    badge: 'bestseller',
  },
  {
    id: '12',
    handle: 'black-faded-loose-fit-pants',
    title: 'Black Faded Loose Fit Pants',
    description: 'Faded black loose fit pants for a vintage look.',
    price: 1499,
    compareAtPrice: 1799,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/black-faded-loose-fit-pants-xs-bonkerscorner-store-33695629443172_8f2479fb-0aa3-4f13-a5c0-5d618a68d9cd_800x.jpg?v=1773819043'],
    category: 'women',
    collection: ['women', 'bottoms'],
    tags: ['black', 'faded', 'pants'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black'],
  },
  {
    id: '13',
    handle: 'black-wide-leg-sweatpants',
    title: 'Black Wide-Leg Sweatpants',
    description: 'Comfortable wide-leg sweatpants in black.',
    price: 1199,
    compareAtPrice: 1499,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/preview_images/9bcf2aa5b920488e890222519957c2a7.thumbnail.0000000000_800x.jpg?v=1773832456'],
    category: 'women',
    collection: ['women', 'bottoms'],
    tags: ['black', 'sweatpants'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black'],
  },
  {
    id: '14',
    handle: 'sand-beige-wide-leg-sweatpants',
    title: 'Sand Beige Wide-Leg Sweatpants',
    description: 'Soft sand beige wide-leg sweatpants.',
    price: 1199,
    compareAtPrice: 1499,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/preview_images/cb1cfb2b132d438fb6432318934bb144.thumbnail.0000000000_800x.jpg?v=1773833326'],
    category: 'women',
    collection: ['women', 'bottoms'],
    tags: ['beige', 'sweatpants'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Beige'],
  },
  {
    id: '15',
    handle: 'kid-98-cap',
    title: 'Kid 98 Cap',
    description: 'Classic 98 cap with kid branding.',
    price: 799,
    compareAtPrice: 1099,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/01_f0bc4625-2505-4593-bdda-b2925af63756_800x.png?v=1787293179'],
    category: 'accessories',
    collection: ['caps'],
    tags: ['cap', 'kid'],
    sizes: ['One Size'],
    colors: ['Black'],
    badge: 'sale',
  },
  {
    id: '16',
    handle: 'soft-yellow-oversized-t-shirt',
    title: 'Soft Yellow Oversized T-shirt',
    description: 'Soft yellow oversized t-shirt for a fresh summer look.',
    price: 999,
    compareAtPrice: 1299,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/SoftYellowOversizedT-shirt_2_800x.png?v=1787831460'],
    category: 'men',
    collection: ['new-arrivals', 'oversized-t-shirts'],
    tags: ['yellow', 'oversized'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Yellow'],
    badge: 'sale',
  },
  {
    id: '17',
    handle: 'iron-grey-oversized-t-shirt',
    title: 'Iron Grey Oversized T-shirt',
    description: 'Premium iron grey oversized t-shirt.',
    price: 999,
    compareAtPrice: 1299,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/IronGreyOversizedT-shirt_2_800x.png?v=1787829068'],
    category: 'men',
    collection: ['new-arrivals', 'oversized-t-shirts'],
    tags: ['grey', 'oversized'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Grey'],
    badge: 'sale',
  },
  {
    id: '18',
    handle: 'blissful-blue-loose-fit-joggers',
    title: 'Blissful Blue Loose Fit Joggers',
    description: 'Comfortable blue loose fit joggers.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://www.bonkerscorner.com/cdn/shop/files/BlissfulBlueLooseFitJoggers_1_148f9233-4125-451b-b9d7-cc06e8942d86_800x.jpg?v=1787295206'],
    category: 'men',
    collection: ['new-arrivals', 'joggers'],
    tags: ['blue', 'joggers'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    badge: 'sale',
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    handle: 'gift-ideas-for-raksha-bandhan',
    title: 'Gift Ideas for Raksha Bandhan: Celebrate Your Sibling Bond in MARVVN Style',
    excerpt: 'Raksha Bandhan just got better. Explore stylish gift ideas for your sibling, from oversized T-shirts and cargos to co-ords, bags and accessories.',
    image: 'https://www.bonkerscorner.com/cdn/shop/articles/RakshaBandhan_jpg_800x.jpg?v=1787397892',
    date: 'August 22 2026',
    author: 'MARVVN',
    tags: ['gifting', 'raksha-bandhan', 'style'],
  },
  {
    id: '2',
    handle: 'how-to-style-cargo-pants',
    title: 'How to Style Cargo Pants for an Effortlessly Balanced Look',
    excerpt: 'Cargo pants are doing the heavy lifting literally. From oversized streetwear fits to polished everyday looks, discover easy ways to style cargos.',
    image: 'https://www.bonkerscorner.com/cdn/shop/articles/Style_Cargo_Pants_Blog_Banner_1__page-0001_b1147022-e607-424c-8a2c-c52238a08590_800x.jpg?v=1786600971',
    date: 'August 13 2026',
    author: 'MARVVN',
    tags: ['cargo', 'styling', 'menswear'],
  },
  {
    id: '3',
    handle: 'spiderman-movie-outfit-ideas',
    title: 'What to Wear to the Spider-Man Movie: Spiderman Outfit Ideas',
    excerpt: 'Your ticket is booked now complete the mission! Explore Spider-Man movie outfit ideas that will have every Marvel fan turning heads.',
    image: 'https://www.bonkerscorner.com/cdn/shop/articles/WhatsApp_Image_2026-07-24_at_3.26.16_PM_800x.jpg?v=1785138333',
    date: 'July 25 2026',
    author: 'MARVVN',
    tags: ['marvel', 'spiderman', 'outfit'],
  },
]

export const collections = [
  { id: '1', handle: 'new-arrivals', title: 'New Arrivals', description: 'Latest drops and fresh fits' },
  { id: '2', handle: 'best-sellers', title: 'Best Sellers', description: 'Handpicked and crafted for you' },
  { id: '3', handle: 'oversized-t-shirts', title: 'Oversized T-Shirts', description: 'Premium oversized tees' },
  { id: '4', handle: 'bottoms', title: 'Bottoms', description: 'Joggers, pants, and more' },
  { id: '5', handle: 'jackets', title: 'Jackets', description: 'Layer up in style' },
  { id: '6', handle: 'caps', title: 'Caps', description: 'Top off your look' },
]