-- Additional products for MARVVN
-- Run this in your Supabase SQL Editor after the main schema

INSERT INTO products (handle, title, description, price, compare_at_price, images, category, collection, tags, sizes, colors, is_new, is_bestseller, badge)
VALUES
  ('ninja-oversized-t-shirt', 'Ninja Oversized T-shirt', 'Stealth-inspired ninja graphic oversized tee.', 999, 1299, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/NinjaOversizedT-shirt_2_800x.jpg?v=1787828213'], 'men', ARRAY['new-arrivals', 'oversized-t-shirts'], ARRAY['ninja', 'oversized'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black'], true, false, 'sale'),
  ('rust-oversized-t-shirt', 'Rust Oversized T-shirt', 'Earthy rust-toned oversized t-shirt.', 999, 1299, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/RustOversizedT-shirt_2_800x.png?v=1787829826'], 'men', ARRAY['new-arrivals', 'oversized-t-shirts'], ARRAY['rust', 'oversized'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Rust'], true, false, 'sale'),
  ('white-oversized-t-shirt', 'White Essentials Oversized T-shirt', 'Clean white oversized tee for everyday wear.', 899, 1199, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/WhiteEssentialsOversizedT-shirt_2_800x.png?v=1787830556'], 'men', ARRAY['best-sellers', 'oversized-t-shirts'], ARRAY['white', 'oversized', 'essential'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['White'], false, true, 'bestseller'),
  ('racing-green-cargo-joggers', 'Racing Green Cargo Joggers', 'Utility-inspired cargo joggers in racing green.', 1499, 1799, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/RacingGreenCargoJoggers_2_800x.jpg?v=1787294119'], 'men', ARRAY['new-arrivals', 'joggers'], ARRAY['green', 'cargo', 'joggers'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Green'], true, false, 'sale'),
  ('shadow-oversized-t-shirt', 'Shadow Oversized T-shirt', 'Dark shadow graphic oversized t-shirt.', 999, 1299, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/ShadowOversizedT-shirt_2_800x.jpg?v=1787830166'], 'women', ARRAY['new-arrivals', 'oversized-t-shirts'], ARRAY['shadow', 'oversized'], ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black'], true, false, 'sale'),
  ('dark-green-oversized-t-shirt', 'Dark Green Oversized T-shirt', 'Rich dark green oversized tee.', 999, 1299, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/DarkGreenOversizedT-shirt_2_800x.png?v=1787828778'], 'women', ARRAY['new-arrivals', 'oversized-t-shirts'], ARRAY['green', 'oversized'], ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'], ARRAY['Green'], true, false, 'sale'),
  ('black-relaxed-fit-cargos', 'Black Relaxed Fit Cargos', 'Relaxed fit cargo pants in black.', 1699, 1999, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/BlackRelaxedFitCargos_2_800x.jpg?v=1787293651'], 'men', ARRAY['best-sellers', 'bottoms'], ARRAY['black', 'cargo', 'pants'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black'], false, true, 'bestseller'),
  ('cream-relaxed-fit-cargos', 'Cream Relaxed Fit Cargos', 'Comfortable cream cargo pants for a relaxed look.', 1699, 1999, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/CreamRelaxedFitCargos_2_800x.jpg?v=1787293420'], 'men', ARRAY['new-arrivals', 'bottoms'], ARRAY['cream', 'cargo', 'pants'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Cream'], true, false, 'sale'),
  ('red-oversized-t-shirt', 'Red Oversized T-shirt', 'Bold red oversized tee to make a statement.', 999, 1299, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/RedOversizedT-shirt_2_800x.png?v=1787829964'], 'women', ARRAY['new-arrivals', 'oversized-t-shirts'], ARRAY['red', 'oversized'], ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'], ARRAY['Red'], true, false, 'sale'),
  ('butterfly-oversized-t-shirt', 'Butterfly Oversized T-shirt', 'Delicate butterfly print oversized tee.', 1099, 1399, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/ButterflyOversizedT-shirt_2_800x.jpg?v=1787826347'], 'women', ARRAY['new-arrivals', 'oversized-t-shirts'], ARRAY['butterfly', 'oversized'], ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'], ARRAY['White'], true, false, 'new'),
  ('black-oversized-hoodie', 'Black Oversized Hoodie', 'Premium heavyweight black oversized hoodie.', 2499, 2999, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/BlackOversizedHoodie_2_800x.jpg?v=1787292936'], 'men', ARRAY['best-sellers', 'sweatshirts-hoodies'], ARRAY['black', 'hoodie', 'oversized'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black'], false, true, 'bestseller'),
  ('grey-oversized-sweatshirt', 'Grey Oversized Sweatshirt', 'Cozy grey oversized sweatshirt for layering.', 1999, 2499, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/GreyOversizedSweatshirt_2_800x.jpg?v=1787295024'], 'men', ARRAY['new-arrivals', 'sweatshirts-hoodies'], ARRAY['grey', 'sweatshirt', 'oversized'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Grey'], true, false, 'sale'),
  ('zip-through-hoodie', 'Zip Through Hoodie', 'Classic zip-through hoodie in navy.', 2199, 2599, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/ZipThroughHoodie_2_800x.jpg?v=1787295799'], 'men', ARRAY['new-arrivals', 'sweatshirts-hoodies'], ARRAY['zip', 'hoodie'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Navy'], true, false, 'sale'),
  ('looney-tunes-oversized-t-shirt', 'Looney Tunes Oversized T-shirt', 'Fun Looney Tunes collab oversized tee.', 1199, 1499, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/LooneyTunesOversizedT-shirt_2_800x.jpg?v=1787827670'], 'women', ARRAY['new-arrivals', 'oversized-t-shirts'], ARRAY['looney', 'tunes', 'oversized', 'anime'], ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'], ARRAY['White'], true, false, 'new'),
  ('marvel-spider-man-oversized-t-shirt', 'Marvel Spider-Man Oversized T-shirt', 'Spider-Man marquee oversized tee for Marvel fans.', 1299, 1599, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/MarvelSpiderManOversizedT-shirt_2_800x.jpg?v=1787827985'], 'men', ARRAY['new-arrivals', 'oversized-t-shirts'], ARRAY['spider-man', 'marvel', 'oversized', 'anime'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Red'], true, false, 'new'),
  ('knitted-beanie', 'Knitted Beanie', 'Cozy knitted beanie to complete your streetwear fit.', 599, 899, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/KnittedBeanie_2_800x.jpg?v=1787293938'], 'accessories', ARRAY['caps'], ARRAY['beanie', 'knitted'], ARRAY['One Size'], ARRAY['Black'], false, false, 'sale'),
  ('red-bull-x-marvvn-oversized-t-shirt', 'Red Bull x MARVVN Oversized T-shirt', 'Official Red Bull collaboration oversized tee.', 1499, 1799, ARRAY['https://www.bonkerscorner.com/cdn/shop/files/RedBullxMARVVNOversizedT-shirt_2_800x.jpg?v=1787829601'], 'men', ARRAY['new-arrivals', 'oversized-t-shirts'], ARRAY['red-bull', 'collab', 'oversized'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Navy'], true, false, 'new')
ON CONFLICT (handle) DO NOTHING;
